### ISSUE TITLE
Support for other SRS

### ISSUE THREAD

**Issue by bchartier** [Oslandia/postile#1]
Postile seems to only support table stored in EPSG:3857. Am I right? Did I miss something?
Is there any plan to let PostGIS reproject the geometries in that SRS when this is not the one used for the storage in PosgreSQL?

**Comment by bchartier** [comment]
If the use of EPSG:3857 for data storage is required, it would be great to mention it in the docs.

**Comment by ldgeo** [comment]
yes thanks for pointing this out, the reprojection to any projection in output is planned, it should be a query parameter like that : 

    /1/1/1.pbf?srs=2154

**Comment by bchartier** [comment]
My suggestion was not to support any projection in the output pbf file but to take into account the projection of the data in PostgreSQL. Few people use 3857 to store their data.
In my humble opinion, there is no need to support other SRS than 3857 in the ouput.

**Comment by ldgeo** [comment]
sorry i read too fast, i was one step ahead, we need first to handle the data projection in the database, 
but next to that we already have some usecases where we want other SRS than 3857 in outputs so both of them will be done.

For per layer access It will be probably a performance issue since we need to query the SRID of the layer dynamically.
For tm2 sources it should not be a problem.

**Comment by ldgeo** [comment]
Done for single layer access. For tm2 sources, it will be quite hard to handle since SQL requests  
can be very complex. Thus i think the projection should be handled directly in database for this later use case. 
 
For other SRS on output, we will add a dedicated endpoint, since it cannot be compatible with the standard tile scheme URLs based on the Spherical Mercator projection.

**Comment by bchartier** [comment]
> Done for single layer access. For tm2 sources, it will be quite hard to handle since SQL requests
> can be very complex. Thus i think the projection should be handled directly in database for this later use case.

Good.
